
2106016b [PULLING] [2020-04-24T06:44:35Z] || image already found, skipping pull phase: docker.io/determinedai/environments:cuda-10.0-pytorch-1.4-tf-1.14-gpu-90bf50b
2106016b [STARTING] [2020-04-24T06:44:35Z] || copying files to container: /
2106016b [STARTING] [2020-04-24T06:44:35Z] || copying files to container: /
2106016b [STARTING] [2020-04-24T06:44:35Z] || copying files to container: /run/determined/workdir
2106016b [STARTING] [2020-04-24T06:44:36Z] || copying files to container: /
2106016b [RUNNING] [2020-04-24T06:44:36Z] ||  + WORKING_DIR=/run/determined/workdir
2106016b [RUNNING] [2020-04-24T06:44:36Z] ||  + STARTUP_HOOK=./startup-hook.sh
2106016b [RUNNING] [2020-04-24T06:44:36Z] ||  + export PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2106016b [RUNNING] [2020-04-24T06:44:36Z] ||  + PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2106016b [RUNNING] [2020-04-24T06:44:36Z] ||  + python3.6 -m pip install --user /opt/determined/wheels/determined-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Processing /opt/determined/wheels/determined-0.12.2-py3-none-any.whl
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Processing /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Processing /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: psutil in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (5.7.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: yogadl==0.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.1)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: cloudpickle==0.5.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.5.3)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: lomond==0.3.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.3)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: requests>=2.20.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.23.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: packaging==19.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (19.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: GPUtil==1.4.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.4.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: numpy>=1.16.2 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.18.2)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: simplejson==3.16.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.16.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: matplotlib in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.2.1)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: dill>=0.2.9 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.1.1)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: boto3>=1.9.220 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.12.41)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.10.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: pyzmq==18.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (18.1.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: gitpython==2.1.11 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.1.11)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: python-dateutil==2.8.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.8.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: ruamel.yaml>=0.15.78 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.16.10)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: tabulate>=0.8.3 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.8.7)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: termcolor==1.1.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.1.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: argcomplete==1.9.4 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.9.4)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: hdfs>=2.2.2 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.5.8)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: graphql-core==2.3.1 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.3.1)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: dai-sgqlc-3.5 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.0.1.dev20200211)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: pathspec>=0.6.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.8.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: google-cloud-storage>=1.20.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (1.27.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: websockets in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (8.1)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: async-generator in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (1.10)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: lmdb in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (0.98)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: filelock in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (3.0.12)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: six>=1.10.0 in /opt/conda/lib/python3.6/site-packages (from lomond==0.3.3->determined==0.12.2) (1.14.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2020.4.5.1)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2.9)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (1.25.8)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (3.0.4)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from packaging==19.0->determined==0.12.2) (2.4.7)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (0.10.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (1.2.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.3.3)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: botocore<1.16.0,>=1.15.41 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (1.15.41)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.9.5)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: gitdb2>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from gitpython==2.1.11->determined-cli==0.12.2) (4.0.2)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /opt/conda/lib/python3.6/site-packages (from ruamel.yaml>=0.15.78->determined-cli==0.12.2) (0.2.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: docopt in /opt/conda/lib/python3.6/site-packages (from hdfs>=2.2.2->determined-common==0.12.2) (0.6.2)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: promise<3,>=2.3 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (2.3)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: rx<2,>=1.6 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (1.6.1)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: google-cloud-core<2.0dev,>=1.2.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.3.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: google-resumable-media<0.6dev,>=0.5.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.5.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: google-auth<2.0dev,>=1.11.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.14.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: docutils<0.16,>=0.10 in /opt/conda/lib/python3.6/site-packages (from botocore<1.16.0,>=1.15.41->boto3>=1.9.220->determined==0.12.2) (0.15.2)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: gitdb>=4.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (4.0.4)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: google-api-core<2.0.0dev,>=1.16.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.17.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.2.8)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.1.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: rsa<4.1,>=3.1.4 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (46.1.3.post20200330)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: smmap<4,>=3.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb>=4.0.1->gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (3.0.2)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.51.0)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: pytz in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (2019.3)
2106016b [RUNNING] [2020-04-24T06:44:37Z] ||  Requirement already satisfied: protobuf>=3.4.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (3.11.3)
2106016b [RUNNING] [2020-04-24T06:44:38Z] ||  Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.4.8)
2106016b [RUNNING] [2020-04-24T06:44:38Z] ||  Installing collected packages: determined-common, determined, determined-cli
2106016b [RUNNING] [2020-04-24T06:44:38Z] ||  Successfully installed determined-0.12.2 determined-cli-0.12.2 determined-common-0.12.2
2106016b [RUNNING] [2020-04-24T06:44:38Z] ||  + cd /run/determined/workdir
2106016b [RUNNING] [2020-04-24T06:44:38Z] ||  + test -f ./startup-hook.sh
2106016b [RUNNING] [2020-04-24T06:44:38Z] ||  + exec python3.6 -m determined.exec.harness
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||  Traceback (most recent call last):
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||      "__main__", mod_spec)
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||      exec(code, run_globals)
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 209, in <module>
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||      main()
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 168, in main
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||      gpu_uuids = gpu.get_gpu_uuids_and_validate(use_gpu, slot_ids)
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 21, in get_gpu_uuids_and_validate
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||      _, gpu_uuids = get_gpu_ids_and_uuids()
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 13, in get_gpu_ids_and_uuids
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||      gpus = GPUtil.getGPUs()
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||    File "/opt/conda/lib/python3.6/site-packages/GPUtil/GPUtil.py", line 102, in getGPUs
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||      deviceIds = int(vals[i])
2106016b [RUNNING] [2020-04-24T06:44:40Z] ||  ValueError: invalid literal for int() with base 10: 'Unable to determine the device handle for GPU 0000:06:00.0: Unknown Error'
812a809a [PULLING] [2020-04-24T06:44:40Z] || image already found, skipping pull phase: docker.io/determinedai/environments:cuda-10.0-pytorch-1.4-tf-1.14-gpu-90bf50b
812a809a [STARTING] [2020-04-24T06:44:40Z] || copying files to container: /
812a809a [STARTING] [2020-04-24T06:44:40Z] || copying files to container: /
812a809a [STARTING] [2020-04-24T06:44:40Z] || copying files to container: /run/determined/workdir
812a809a [STARTING] [2020-04-24T06:44:40Z] || copying files to container: /
812a809a [RUNNING] [2020-04-24T06:44:41Z] ||  + WORKING_DIR=/run/determined/workdir
812a809a [RUNNING] [2020-04-24T06:44:41Z] ||  + STARTUP_HOOK=./startup-hook.sh
812a809a [RUNNING] [2020-04-24T06:44:41Z] ||  + export PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
812a809a [RUNNING] [2020-04-24T06:44:41Z] ||  + PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
812a809a [RUNNING] [2020-04-24T06:44:41Z] ||  + python3.6 -m pip install --user /opt/determined/wheels/determined-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Processing /opt/determined/wheels/determined-0.12.2-py3-none-any.whl
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Processing /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Processing /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: psutil in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (5.7.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: yogadl==0.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.1)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: cloudpickle==0.5.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.5.3)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: lomond==0.3.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.3)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: GPUtil==1.4.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.4.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: packaging==19.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (19.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: numpy>=1.16.2 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.18.2)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: simplejson==3.16.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.16.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: matplotlib in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.2.1)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: requests>=2.20.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.23.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: dill>=0.2.9 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.1.1)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: boto3>=1.9.220 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.12.41)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.10.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: pyzmq==18.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (18.1.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: gitpython==2.1.11 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.1.11)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: python-dateutil==2.8.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.8.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: ruamel.yaml>=0.15.78 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.16.10)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: tabulate>=0.8.3 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.8.7)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: termcolor==1.1.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.1.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: argcomplete==1.9.4 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.9.4)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: hdfs>=2.2.2 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.5.8)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: graphql-core==2.3.1 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.3.1)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: dai-sgqlc-3.5 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.0.1.dev20200211)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: pathspec>=0.6.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.8.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: google-cloud-storage>=1.20.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (1.27.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: websockets in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (8.1)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: async-generator in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (1.10)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: lmdb in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (0.98)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: filelock in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (3.0.12)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: six>=1.10.0 in /opt/conda/lib/python3.6/site-packages (from lomond==0.3.3->determined==0.12.2) (1.14.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from packaging==19.0->determined==0.12.2) (2.4.7)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (0.10.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (1.2.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2020.4.5.1)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2.9)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (1.25.8)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (3.0.4)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.3.3)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: botocore<1.16.0,>=1.15.41 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (1.15.41)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.9.5)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: gitdb2>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from gitpython==2.1.11->determined-cli==0.12.2) (4.0.2)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /opt/conda/lib/python3.6/site-packages (from ruamel.yaml>=0.15.78->determined-cli==0.12.2) (0.2.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: docopt in /opt/conda/lib/python3.6/site-packages (from hdfs>=2.2.2->determined-common==0.12.2) (0.6.2)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: promise<3,>=2.3 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (2.3)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: rx<2,>=1.6 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (1.6.1)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: google-cloud-core<2.0dev,>=1.2.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.3.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: google-resumable-media<0.6dev,>=0.5.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.5.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: google-auth<2.0dev,>=1.11.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.14.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: docutils<0.16,>=0.10 in /opt/conda/lib/python3.6/site-packages (from botocore<1.16.0,>=1.15.41->boto3>=1.9.220->determined==0.12.2) (0.15.2)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: gitdb>=4.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (4.0.4)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: google-api-core<2.0.0dev,>=1.16.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.17.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.2.8)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.1.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: rsa<4.1,>=3.1.4 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (46.1.3.post20200330)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: smmap<4,>=3.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb>=4.0.1->gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (3.0.2)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.51.0)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: pytz in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (2019.3)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: protobuf>=3.4.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (3.11.3)
812a809a [RUNNING] [2020-04-24T06:44:42Z] ||  Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.4.8)
812a809a [RUNNING] [2020-04-24T06:44:43Z] ||  Installing collected packages: determined-common, determined, determined-cli
812a809a [RUNNING] [2020-04-24T06:44:43Z] ||  Successfully installed determined-0.12.2 determined-cli-0.12.2 determined-common-0.12.2
812a809a [RUNNING] [2020-04-24T06:44:43Z] ||  + cd /run/determined/workdir
812a809a [RUNNING] [2020-04-24T06:44:43Z] ||  + test -f ./startup-hook.sh
812a809a [RUNNING] [2020-04-24T06:44:43Z] ||  + exec python3.6 -m determined.exec.harness
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||  Traceback (most recent call last):
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||      "__main__", mod_spec)
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||      exec(code, run_globals)
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 209, in <module>
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||      main()
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 168, in main
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||      gpu_uuids = gpu.get_gpu_uuids_and_validate(use_gpu, slot_ids)
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 21, in get_gpu_uuids_and_validate
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||      _, gpu_uuids = get_gpu_ids_and_uuids()
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 13, in get_gpu_ids_and_uuids
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||      gpus = GPUtil.getGPUs()
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||    File "/opt/conda/lib/python3.6/site-packages/GPUtil/GPUtil.py", line 102, in getGPUs
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||      deviceIds = int(vals[i])
812a809a [RUNNING] [2020-04-24T06:44:44Z] ||  ValueError: invalid literal for int() with base 10: 'Unable to determine the device handle for GPU 0000:06:00.0: Unknown Error'
cd240eda [PULLING] [2020-04-24T06:44:45Z] || image already found, skipping pull phase: docker.io/determinedai/environments:cuda-10.0-pytorch-1.4-tf-1.14-gpu-90bf50b
cd240eda [STARTING] [2020-04-24T06:44:45Z] || copying files to container: /
cd240eda [STARTING] [2020-04-24T06:44:45Z] || copying files to container: /
cd240eda [STARTING] [2020-04-24T06:44:45Z] || copying files to container: /run/determined/workdir
cd240eda [STARTING] [2020-04-24T06:44:45Z] || copying files to container: /
cd240eda [RUNNING] [2020-04-24T06:44:46Z] ||  + WORKING_DIR=/run/determined/workdir
cd240eda [RUNNING] [2020-04-24T06:44:46Z] ||  + STARTUP_HOOK=./startup-hook.sh
cd240eda [RUNNING] [2020-04-24T06:44:46Z] ||  + export PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
cd240eda [RUNNING] [2020-04-24T06:44:46Z] ||  + PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
cd240eda [RUNNING] [2020-04-24T06:44:46Z] ||  + python3.6 -m pip install --user /opt/determined/wheels/determined-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Processing /opt/determined/wheels/determined-0.12.2-py3-none-any.whl
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Processing /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Processing /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: psutil in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (5.7.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: yogadl==0.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.1)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: cloudpickle==0.5.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.5.3)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: lomond==0.3.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.3)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: requests>=2.20.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.23.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: packaging==19.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (19.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: GPUtil==1.4.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.4.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: numpy>=1.16.2 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.18.2)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: simplejson==3.16.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.16.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: matplotlib in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.2.1)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: dill>=0.2.9 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.1.1)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: boto3>=1.9.220 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.12.41)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.10.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: pyzmq==18.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (18.1.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: gitpython==2.1.11 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.1.11)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: python-dateutil==2.8.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.8.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: ruamel.yaml>=0.15.78 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.16.10)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: tabulate>=0.8.3 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.8.7)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: termcolor==1.1.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.1.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: argcomplete==1.9.4 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.9.4)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: hdfs>=2.2.2 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.5.8)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: graphql-core==2.3.1 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.3.1)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: dai-sgqlc-3.5 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.0.1.dev20200211)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: pathspec>=0.6.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.8.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: google-cloud-storage>=1.20.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (1.27.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: websockets in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (8.1)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: async-generator in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (1.10)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: lmdb in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (0.98)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: filelock in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (3.0.12)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: six>=1.10.0 in /opt/conda/lib/python3.6/site-packages (from lomond==0.3.3->determined==0.12.2) (1.14.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2020.4.5.1)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2.9)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (1.25.8)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (3.0.4)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from packaging==19.0->determined==0.12.2) (2.4.7)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (0.10.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (1.2.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.3.3)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: botocore<1.16.0,>=1.15.41 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (1.15.41)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.9.5)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: gitdb2>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from gitpython==2.1.11->determined-cli==0.12.2) (4.0.2)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /opt/conda/lib/python3.6/site-packages (from ruamel.yaml>=0.15.78->determined-cli==0.12.2) (0.2.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: docopt in /opt/conda/lib/python3.6/site-packages (from hdfs>=2.2.2->determined-common==0.12.2) (0.6.2)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: promise<3,>=2.3 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (2.3)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: rx<2,>=1.6 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (1.6.1)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: google-cloud-core<2.0dev,>=1.2.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.3.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: google-resumable-media<0.6dev,>=0.5.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.5.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: google-auth<2.0dev,>=1.11.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.14.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: docutils<0.16,>=0.10 in /opt/conda/lib/python3.6/site-packages (from botocore<1.16.0,>=1.15.41->boto3>=1.9.220->determined==0.12.2) (0.15.2)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: gitdb>=4.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (4.0.4)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: google-api-core<2.0.0dev,>=1.16.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.17.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.2.8)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.1.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: rsa<4.1,>=3.1.4 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (46.1.3.post20200330)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: smmap<4,>=3.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb>=4.0.1->gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (3.0.2)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.51.0)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: pytz in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (2019.3)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: protobuf>=3.4.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (3.11.3)
cd240eda [RUNNING] [2020-04-24T06:44:47Z] ||  Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.4.8)
cd240eda [RUNNING] [2020-04-24T06:44:48Z] ||  Installing collected packages: determined-common, determined, determined-cli
cd240eda [RUNNING] [2020-04-24T06:44:48Z] ||  Successfully installed determined-0.12.2 determined-cli-0.12.2 determined-common-0.12.2
cd240eda [RUNNING] [2020-04-24T06:44:48Z] ||  + cd /run/determined/workdir
cd240eda [RUNNING] [2020-04-24T06:44:48Z] ||  + test -f ./startup-hook.sh
cd240eda [RUNNING] [2020-04-24T06:44:48Z] ||  + exec python3.6 -m determined.exec.harness
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||  Traceback (most recent call last):
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||      "__main__", mod_spec)
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||      exec(code, run_globals)
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 209, in <module>
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||      main()
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 168, in main
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||      gpu_uuids = gpu.get_gpu_uuids_and_validate(use_gpu, slot_ids)
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 21, in get_gpu_uuids_and_validate
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||      _, gpu_uuids = get_gpu_ids_and_uuids()
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 13, in get_gpu_ids_and_uuids
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||      gpus = GPUtil.getGPUs()
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||    File "/opt/conda/lib/python3.6/site-packages/GPUtil/GPUtil.py", line 102, in getGPUs
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||      deviceIds = int(vals[i])
cd240eda [RUNNING] [2020-04-24T06:44:49Z] ||  ValueError: invalid literal for int() with base 10: 'Unable to determine the device handle for GPU 0000:06:00.0: Unknown Error'
c5719584 [PULLING] [2020-04-24T06:44:50Z] || image already found, skipping pull phase: docker.io/determinedai/environments:cuda-10.0-pytorch-1.4-tf-1.14-gpu-90bf50b
c5719584 [STARTING] [2020-04-24T06:44:50Z] || copying files to container: /
c5719584 [STARTING] [2020-04-24T06:44:50Z] || copying files to container: /
c5719584 [STARTING] [2020-04-24T06:44:50Z] || copying files to container: /run/determined/workdir
c5719584 [STARTING] [2020-04-24T06:44:50Z] || copying files to container: /
c5719584 [RUNNING] [2020-04-24T06:44:51Z] ||  + WORKING_DIR=/run/determined/workdir
c5719584 [RUNNING] [2020-04-24T06:44:51Z] ||  + STARTUP_HOOK=./startup-hook.sh
c5719584 [RUNNING] [2020-04-24T06:44:51Z] ||  + export PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
c5719584 [RUNNING] [2020-04-24T06:44:51Z] ||  + PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
c5719584 [RUNNING] [2020-04-24T06:44:51Z] ||  + python3.6 -m pip install --user /opt/determined/wheels/determined-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Processing /opt/determined/wheels/determined-0.12.2-py3-none-any.whl
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Processing /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Processing /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: psutil in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (5.7.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: yogadl==0.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.1)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: cloudpickle==0.5.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.5.3)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: lomond==0.3.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.3)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: requests>=2.20.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.23.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: packaging==19.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (19.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: GPUtil==1.4.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.4.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: numpy>=1.16.2 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.18.2)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: simplejson==3.16.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.16.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: matplotlib in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.2.1)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: dill>=0.2.9 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.1.1)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: boto3>=1.9.220 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.12.41)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.10.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: pyzmq==18.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (18.1.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: gitpython==2.1.11 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.1.11)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: python-dateutil==2.8.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.8.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: ruamel.yaml>=0.15.78 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.16.10)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: tabulate>=0.8.3 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.8.7)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: termcolor==1.1.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.1.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: argcomplete==1.9.4 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.9.4)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: hdfs>=2.2.2 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.5.8)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: graphql-core==2.3.1 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.3.1)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: dai-sgqlc-3.5 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.0.1.dev20200211)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: pathspec>=0.6.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.8.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: google-cloud-storage>=1.20.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (1.27.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: websockets in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (8.1)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: async-generator in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (1.10)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: lmdb in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (0.98)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: filelock in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (3.0.12)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: six>=1.10.0 in /opt/conda/lib/python3.6/site-packages (from lomond==0.3.3->determined==0.12.2) (1.14.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2020.4.5.1)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2.9)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (1.25.8)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (3.0.4)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from packaging==19.0->determined==0.12.2) (2.4.7)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (0.10.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (1.2.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.3.3)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: botocore<1.16.0,>=1.15.41 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (1.15.41)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.9.5)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: gitdb2>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from gitpython==2.1.11->determined-cli==0.12.2) (4.0.2)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /opt/conda/lib/python3.6/site-packages (from ruamel.yaml>=0.15.78->determined-cli==0.12.2) (0.2.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: docopt in /opt/conda/lib/python3.6/site-packages (from hdfs>=2.2.2->determined-common==0.12.2) (0.6.2)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: promise<3,>=2.3 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (2.3)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: rx<2,>=1.6 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (1.6.1)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: google-cloud-core<2.0dev,>=1.2.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.3.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: google-resumable-media<0.6dev,>=0.5.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.5.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: google-auth<2.0dev,>=1.11.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.14.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: docutils<0.16,>=0.10 in /opt/conda/lib/python3.6/site-packages (from botocore<1.16.0,>=1.15.41->boto3>=1.9.220->determined==0.12.2) (0.15.2)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: gitdb>=4.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (4.0.4)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: google-api-core<2.0.0dev,>=1.16.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.17.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.2.8)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.1.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: rsa<4.1,>=3.1.4 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (46.1.3.post20200330)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: smmap<4,>=3.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb>=4.0.1->gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (3.0.2)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.51.0)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: pytz in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (2019.3)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: protobuf>=3.4.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (3.11.3)
c5719584 [RUNNING] [2020-04-24T06:44:52Z] ||  Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.4.8)
c5719584 [RUNNING] [2020-04-24T06:44:53Z] ||  Installing collected packages: determined-common, determined, determined-cli
c5719584 [RUNNING] [2020-04-24T06:44:53Z] ||  Successfully installed determined-0.12.2 determined-cli-0.12.2 determined-common-0.12.2
c5719584 [RUNNING] [2020-04-24T06:44:53Z] ||  + cd /run/determined/workdir
c5719584 [RUNNING] [2020-04-24T06:44:53Z] ||  + test -f ./startup-hook.sh
c5719584 [RUNNING] [2020-04-24T06:44:53Z] ||  + exec python3.6 -m determined.exec.harness
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||  Traceback (most recent call last):
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||      "__main__", mod_spec)
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||      exec(code, run_globals)
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 209, in <module>
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||      main()
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 168, in main
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||      gpu_uuids = gpu.get_gpu_uuids_and_validate(use_gpu, slot_ids)
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 21, in get_gpu_uuids_and_validate
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||      _, gpu_uuids = get_gpu_ids_and_uuids()
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 13, in get_gpu_ids_and_uuids
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||      gpus = GPUtil.getGPUs()
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||    File "/opt/conda/lib/python3.6/site-packages/GPUtil/GPUtil.py", line 102, in getGPUs
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||      deviceIds = int(vals[i])
c5719584 [RUNNING] [2020-04-24T06:44:54Z] ||  ValueError: invalid literal for int() with base 10: 'Unable to determine the device handle for GPU 0000:06:00.0: Unknown Error'
c8fbf736 [PULLING] [2020-04-24T06:44:55Z] || image already found, skipping pull phase: docker.io/determinedai/environments:cuda-10.0-pytorch-1.4-tf-1.14-gpu-90bf50b
c8fbf736 [STARTING] [2020-04-24T06:44:55Z] || copying files to container: /
c8fbf736 [STARTING] [2020-04-24T06:44:55Z] || copying files to container: /
c8fbf736 [STARTING] [2020-04-24T06:44:55Z] || copying files to container: /run/determined/workdir
c8fbf736 [STARTING] [2020-04-24T06:44:55Z] || copying files to container: /
c8fbf736 [RUNNING] [2020-04-24T06:44:56Z] ||  + WORKING_DIR=/run/determined/workdir
c8fbf736 [RUNNING] [2020-04-24T06:44:56Z] ||  + STARTUP_HOOK=./startup-hook.sh
c8fbf736 [RUNNING] [2020-04-24T06:44:56Z] ||  + export PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
c8fbf736 [RUNNING] [2020-04-24T06:44:56Z] ||  + PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
c8fbf736 [RUNNING] [2020-04-24T06:44:56Z] ||  + python3.6 -m pip install --user /opt/determined/wheels/determined-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Processing /opt/determined/wheels/determined-0.12.2-py3-none-any.whl
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Processing /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Processing /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: psutil in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (5.7.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: yogadl==0.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.1)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: cloudpickle==0.5.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.5.3)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: lomond==0.3.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.3)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: GPUtil==1.4.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.4.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: packaging==19.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (19.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: numpy>=1.16.2 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.18.2)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: simplejson==3.16.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.16.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: matplotlib in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.2.1)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: requests>=2.20.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.23.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: dill>=0.2.9 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.1.1)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: boto3>=1.9.220 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.12.41)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.10.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: pyzmq==18.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (18.1.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: gitpython==2.1.11 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.1.11)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: python-dateutil==2.8.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.8.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: ruamel.yaml>=0.15.78 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.16.10)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: tabulate>=0.8.3 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.8.7)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: termcolor==1.1.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.1.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: argcomplete==1.9.4 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.9.4)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: hdfs>=2.2.2 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.5.8)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: graphql-core==2.3.1 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.3.1)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: dai-sgqlc-3.5 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.0.1.dev20200211)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: pathspec>=0.6.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.8.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: google-cloud-storage>=1.20.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (1.27.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: websockets in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (8.1)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: async-generator in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (1.10)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: lmdb in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (0.98)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: filelock in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (3.0.12)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: six>=1.10.0 in /opt/conda/lib/python3.6/site-packages (from lomond==0.3.3->determined==0.12.2) (1.14.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from packaging==19.0->determined==0.12.2) (2.4.7)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (0.10.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (1.2.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2020.4.5.1)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2.9)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (1.25.8)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (3.0.4)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.3.3)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: botocore<1.16.0,>=1.15.41 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (1.15.41)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.9.5)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: gitdb2>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from gitpython==2.1.11->determined-cli==0.12.2) (4.0.2)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /opt/conda/lib/python3.6/site-packages (from ruamel.yaml>=0.15.78->determined-cli==0.12.2) (0.2.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: docopt in /opt/conda/lib/python3.6/site-packages (from hdfs>=2.2.2->determined-common==0.12.2) (0.6.2)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: promise<3,>=2.3 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (2.3)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: rx<2,>=1.6 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (1.6.1)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: google-cloud-core<2.0dev,>=1.2.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.3.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: google-resumable-media<0.6dev,>=0.5.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.5.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: google-auth<2.0dev,>=1.11.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.14.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: docutils<0.16,>=0.10 in /opt/conda/lib/python3.6/site-packages (from botocore<1.16.0,>=1.15.41->boto3>=1.9.220->determined==0.12.2) (0.15.2)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: gitdb>=4.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (4.0.4)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: google-api-core<2.0.0dev,>=1.16.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.17.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.2.8)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.1.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: rsa<4.1,>=3.1.4 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (46.1.3.post20200330)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: smmap<4,>=3.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb>=4.0.1->gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (3.0.2)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.51.0)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: pytz in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (2019.3)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: protobuf>=3.4.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (3.11.3)
c8fbf736 [RUNNING] [2020-04-24T06:44:57Z] ||  Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.4.8)
c8fbf736 [RUNNING] [2020-04-24T06:44:58Z] ||  Installing collected packages: determined-common, determined, determined-cli
c8fbf736 [RUNNING] [2020-04-24T06:44:58Z] ||  Successfully installed determined-0.12.2 determined-cli-0.12.2 determined-common-0.12.2
c8fbf736 [RUNNING] [2020-04-24T06:44:58Z] ||  + cd /run/determined/workdir
c8fbf736 [RUNNING] [2020-04-24T06:44:58Z] ||  + test -f ./startup-hook.sh
c8fbf736 [RUNNING] [2020-04-24T06:44:58Z] ||  + exec python3.6 -m determined.exec.harness
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||  Traceback (most recent call last):
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||      "__main__", mod_spec)
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||      exec(code, run_globals)
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 209, in <module>
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||      main()
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 168, in main
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||      gpu_uuids = gpu.get_gpu_uuids_and_validate(use_gpu, slot_ids)
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 21, in get_gpu_uuids_and_validate
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||      _, gpu_uuids = get_gpu_ids_and_uuids()
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 13, in get_gpu_ids_and_uuids
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||      gpus = GPUtil.getGPUs()
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||    File "/opt/conda/lib/python3.6/site-packages/GPUtil/GPUtil.py", line 102, in getGPUs
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||      deviceIds = int(vals[i])
c8fbf736 [RUNNING] [2020-04-24T06:44:59Z] ||  ValueError: invalid literal for int() with base 10: 'Unable to determine the device handle for GPU 0000:06:00.0: Unknown Error'
8a81ede3 [PULLING] [2020-04-24T06:45:00Z] || image already found, skipping pull phase: docker.io/determinedai/environments:cuda-10.0-pytorch-1.4-tf-1.14-gpu-90bf50b
8a81ede3 [STARTING] [2020-04-24T06:45:00Z] || copying files to container: /
8a81ede3 [STARTING] [2020-04-24T06:45:00Z] || copying files to container: /
8a81ede3 [STARTING] [2020-04-24T06:45:00Z] || copying files to container: /run/determined/workdir
8a81ede3 [STARTING] [2020-04-24T06:45:00Z] || copying files to container: /
8a81ede3 [RUNNING] [2020-04-24T06:45:01Z] ||  + WORKING_DIR=/run/determined/workdir
8a81ede3 [RUNNING] [2020-04-24T06:45:01Z] ||  + STARTUP_HOOK=./startup-hook.sh
8a81ede3 [RUNNING] [2020-04-24T06:45:01Z] ||  + export PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
8a81ede3 [RUNNING] [2020-04-24T06:45:01Z] ||  + PATH=/run/determined/pythonuserbase/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
8a81ede3 [RUNNING] [2020-04-24T06:45:01Z] ||  + python3.6 -m pip install --user /opt/determined/wheels/determined-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Processing /opt/determined/wheels/determined-0.12.2-py3-none-any.whl
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Processing /opt/determined/wheels/determined_cli-0.12.2-py3-none-any.whl
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Processing /opt/determined/wheels/determined_common-0.12.2-py3-none-any.whl
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: psutil in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (5.7.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: yogadl==0.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.1)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: cloudpickle==0.5.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.5.3)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: lomond==0.3.3 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.3)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: requests>=2.20.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.23.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: packaging==19.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (19.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: GPUtil==1.4.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.4.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: numpy>=1.16.2 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.18.2)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: simplejson==3.16.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.16.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: matplotlib in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (3.2.1)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: dill>=0.2.9 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (0.3.1.1)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: boto3>=1.9.220 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (1.12.41)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (2.10.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: pyzmq==18.1.0 in /opt/conda/lib/python3.6/site-packages (from determined==0.12.2) (18.1.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: gitpython==2.1.11 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.1.11)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: python-dateutil==2.8.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (2.8.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: ruamel.yaml>=0.15.78 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.16.10)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: tabulate>=0.8.3 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (0.8.7)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: termcolor==1.1.0 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.1.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: argcomplete==1.9.4 in /opt/conda/lib/python3.6/site-packages (from determined-cli==0.12.2) (1.9.4)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: hdfs>=2.2.2 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.5.8)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: graphql-core==2.3.1 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (2.3.1)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: dai-sgqlc-3.5 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.0.1.dev20200211)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: pathspec>=0.6.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (0.8.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: google-cloud-storage>=1.20.0 in /opt/conda/lib/python3.6/site-packages (from determined-common==0.12.2) (1.27.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: websockets in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (8.1)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: async-generator in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (1.10)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: lmdb in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (0.98)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: filelock in /opt/conda/lib/python3.6/site-packages (from yogadl==0.1.0->determined==0.12.2) (3.0.12)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: six>=1.10.0 in /opt/conda/lib/python3.6/site-packages (from lomond==0.3.3->determined==0.12.2) (1.14.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2020.4.5.1)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (2.9)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (1.25.8)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests>=2.20.0->determined==0.12.2) (3.0.4)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from packaging==19.0->determined==0.12.2) (2.4.7)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (0.10.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.6/site-packages (from matplotlib->determined==0.12.2) (1.2.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.3.3)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: botocore<1.16.0,>=1.15.41 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (1.15.41)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9.220->determined==0.12.2) (0.9.5)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: gitdb2>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from gitpython==2.1.11->determined-cli==0.12.2) (4.0.2)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /opt/conda/lib/python3.6/site-packages (from ruamel.yaml>=0.15.78->determined-cli==0.12.2) (0.2.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: docopt in /opt/conda/lib/python3.6/site-packages (from hdfs>=2.2.2->determined-common==0.12.2) (0.6.2)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: promise<3,>=2.3 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (2.3)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: rx<2,>=1.6 in /opt/conda/lib/python3.6/site-packages (from graphql-core==2.3.1->determined-common==0.12.2) (1.6.1)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: google-cloud-core<2.0dev,>=1.2.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.3.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: google-resumable-media<0.6dev,>=0.5.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.5.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: google-auth<2.0dev,>=1.11.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.14.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: docutils<0.16,>=0.10 in /opt/conda/lib/python3.6/site-packages (from botocore<1.16.0,>=1.15.41->boto3>=1.9.220->determined==0.12.2) (0.15.2)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: gitdb>=4.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (4.0.4)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: google-api-core<2.0.0dev,>=1.16.0 in /opt/conda/lib/python3.6/site-packages (from google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.17.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.2.8)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.1.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: rsa<4.1,>=3.1.4 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (4.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (46.1.3.post20200330)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: smmap<4,>=3.0.1 in /opt/conda/lib/python3.6/site-packages (from gitdb>=4.0.1->gitdb2>=2.0.0->gitpython==2.1.11->determined-cli==0.12.2) (3.0.2)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (1.51.0)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: pytz in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (2019.3)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: protobuf>=3.4.0 in /opt/conda/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=1.16.0->google-cloud-core<2.0dev,>=1.2.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (3.11.3)
8a81ede3 [RUNNING] [2020-04-24T06:45:02Z] ||  Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.11.0->google-cloud-storage>=1.20.0->determined-common==0.12.2) (0.4.8)
8a81ede3 [RUNNING] [2020-04-24T06:45:03Z] ||  Installing collected packages: determined-common, determined, determined-cli
8a81ede3 [RUNNING] [2020-04-24T06:45:03Z] ||  Successfully installed determined-0.12.2 determined-cli-0.12.2 determined-common-0.12.2
8a81ede3 [RUNNING] [2020-04-24T06:45:03Z] ||  + cd /run/determined/workdir
8a81ede3 [RUNNING] [2020-04-24T06:45:03Z] ||  + test -f ./startup-hook.sh
8a81ede3 [RUNNING] [2020-04-24T06:45:03Z] ||  + exec python3.6 -m determined.exec.harness
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||  Traceback (most recent call last):
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||      "__main__", mod_spec)
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||    File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||      exec(code, run_globals)
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 209, in <module>
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||      main()
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 168, in main
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||      gpu_uuids = gpu.get_gpu_uuids_and_validate(use_gpu, slot_ids)
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 21, in get_gpu_uuids_and_validate
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||      _, gpu_uuids = get_gpu_ids_and_uuids()
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||    File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/gpu.py", line 13, in get_gpu_ids_and_uuids
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||      gpus = GPUtil.getGPUs()
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||    File "/opt/conda/lib/python3.6/site-packages/GPUtil/GPUtil.py", line 102, in getGPUs
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||      deviceIds = int(vals[i])
8a81ede3 [RUNNING] [2020-04-24T06:45:04Z] ||  ValueError: invalid literal for int() with base 10: 'Unable to determine the device handle for GPU 0000:06:00.0: Unknown Error' 
